os: osx
osx_image: xcode11
language: swift
install:
  - bundle install
  - ./install_swiftlint.sh

script:
  - xcodebuild build -workspace Locatics.xcworkspace -scheme "Locatics" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.0,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

after_success:
- bash <(curl -s https://codecov.io/bash)
