os: osx
osx_image: xcode10.3
language: swift
install:
  - ./install_swiftlint.sh

script:
  - sudo bundle install
  - swiftlint
  - xcodebuild clean build test -workspace Locatics/Locatics.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

after_success:
- bash <(curl -s https://codecov.io/bash)
